### PR TITLE
[catloop] Rollback Port Allocation

### LINKED ISSUE #621: [catloop] Rollback Port Allocation If `accept()` Fails
## Description

We should rollback port allocation if `accept()` fails.

## Code Snippet

https://github.com/demikernel/demikernel/blob/b596f4f115accc8895d6d276c368b59c59948400/src/rust/catloop/mod.rs#L479-L482

### PR DESCRIPTION
**Pull request by carvalhof**
## Description

This PR closes #621

## Summary of Changes

- Updated `CatloopLibOS` inserting the `EphemeralPorts` allocator.
- Allocated ports using the port allocator.
- Rollbacked the port allocation when the `accept` failed.
- Rollbacked the port allocation when the socket closed.

### CODE REVIEW

File: src/rust/catloop/mod.rs [hunk 1]
```diff
@@ -414,6 +428,11 @@ impl CatloopLibOS {
                 if let Some(duplex_pipe) = queue.get_pipe() {
                     duplex_pipe.close()?;
                 }
+                if let Socket::Active(Some(addr)) | Socket::Passive(addr) = queue.get_socket() {
+                    let port: u16 = addr.port();
```
Comment (ppenna) [inline src/rust/catloop/mod.rs:432]: Could you move this bellow the comment?

File: src/rust/catloop/mod.rs [hunk 2]
```diff
@@ -285,11 +292,15 @@ impl CatloopLibOS {
         // Will use this later on close.
         let yielder_handle: YielderHandle = yielder.get_handle();
         let catmem: Rc<RefCell<CatmemLibOS>> = self.catmem.clone();
-        let next_port: u16 = self.next_port;
+        let ephemeral_ptr: Rc<RefCell<EphemeralPorts>> = self.ephemeral_ports.clone();
+        let new_port: u16 = match ephemeral_ports.alloc_any() {
+            Ok(new_port) => new_port,
+            Err(e) => return Err(e)
+        };
```
Comment (ppenna) [inline src/rust/catloop/mod.rs:299]: Could you move the ephemeral port allocation logc just to just after the queue descript allocation?

File: src/rust/catloop/mod.rs [hunk 3]
```diff
@@ -121,8 +126,9 @@ impl CatloopLibOS {
 
     /// Instantiates a new LibOS.
     pub fn new() -> Self {
+        let mut rng: SmallRng = SmallRng::from_entropy();
```
Comment (ppenna) [inline src/rust/catloop/mod.rs:129]: Could you add a configuration statement that would generate this from a fixed seed on debug mode?

Comment (carvalhof) [reply src/rust/catloop/mod.rs:141]: Done.

**Review by ppenna — APPROVED** [review]
LGTM
