### PR TITLE
[catloop] Always Bound Read from Control Duplex Pipe

### LINKED ISSUE #777: [catloop] Resend connect request causes server not to recognize magic number
## Description

Catloop may send more than one connection request on each connect if the server does not immediately respond. Since the memory queues are not lossy, this request gets stuck behind the next one. The next time that the server goes into the accept loop, it will pull both requests out as one pop and not recognize it as a magic number.

## How to Reproduce

1. Run any of the tcp-close tests
2. See invalid request errors on the server side.

## Expected Behavior

The connect should not try again or identify each request in a unique way in addition to the magic number, so that the server does one accept for each connect request. Essentially, we should ensure exactly once RPC on the control pipe or not do an unbounded read and resend the connect request on the client so soon.

### PR DESCRIPTION
**Pull request by iyzhang**
This PR removes the ability to ever ready from the control duplex pipe on the accept with anything other than the size of MAGIC_CONNECT. Because each MAGIC_CONNECT represents a separate connection request, the code will crash if we ever read more than one at a time. Thus, this PR closes #777 by simply removing the ability to read anything from the control duplex pipe that is not a single MAGIC_CONNECT value.

### CODE REVIEW

File: src/rust/catloop/futures/accept.rs [hunk 1]
```diff
@@ -52,32 +52,19 @@ pub async fn accept_coroutine(
...
-            new_duplex_pipe.clone(),
-            Some(mem::size_of_val(&CatloopLibOS::MAGIC_CONNECT)),
-            &yielder,
-        )
-        .await
-        {
+        match pop_magic_number(&catmem, new_duplex_pipe.clone(), &yielder).await {
             // Valid response. Connection successfully established, so return new port and pipe to application.
             Ok(true) => return Ok((SocketAddrV4::new(ipv4.clone(), new_port), new_duplex_pipe.clone())),
             // Invalid reponse.
```
Comment (ppenna) [inline src/rust/catloop/futures/accept.rs:70]: "response" is misspelled.

Comment (iyzhang) [reply src/rust/catloop/futures/accept.rs:70]: I think it is correct?

**Comment by iyzhang** [comment]
> 

We did. I just made it not optional.
