### PR TITLE
[inetstack] Bug Fix: Clamp window scale to 14

### LINKED ISSUE #216: [inetstack] Fail Instead of Panicking on Bad Remote Window Scale
Description
========

In `protocols::tcp::active_open::receive()`, we currently panicking on a bad window scale, instead of failing or rounding down the provided value.

### PR DESCRIPTION
**Pull request by iyzhang**
This closes #216

### CODE REVIEW

File: src/rust/inetstack/protocols/tcp/active_open.rs [hunk 1]
```diff
@@ -180,14 +180,25 @@ impl<N: NetworkRuntime> SharedActiveOpenSocket<N> {
...
+                    self.tcp_config.get_window_scale() as u32
+                };
+                let remote: u8 = if remote_window_scale > 14 {
+                    warn!("remote windows scale larger than 14 is incorrect, so setting to 14. See RFC 1323.");
+                    14
+                } else {
+                    remote_window_scale
+                };
+                (local, remote)
+            },
```
Comment (ppenna) [inline src/rust/inetstack/protocols/tcp/active_open.rs:198]: Can we have a file-scope constant for `14`? Preferrable this should be placed on the same file with other TCP constants.

Comment (iyzhang) [reply src/rust/inetstack/protocols/tcp/active_open.rs:198]: yeah sounds good

**Review by ppenna — APPROVED** [review]
LGTM
